from colors import *
WIDTH = 720
HEIGHT = 600
GUI_WIDTH = 650
GUI_HEIGHT = 500
X_OFF = (WIDTH - GUI_WIDTH) // 2
Y_OFF = int((HEIGHT - GUI_HEIGHT) * 0.8)
FPS = 60
TITLE_FONT = 'comicsansms'
TITLE_FONT_SIZE = 50
BUTTON_FONT = 'consolas'
BUTTON_FONT_SIZE = 20
BUTTON_PRESSED = 'button_p.png'
BUTTON_UNPRESS = 'button_up.png'
BUTTON_LABEL_COLOR = WHITE
BUTTON_LABEL_HOVER_COLOR = PERU